image: debian:stable

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apt-get update -qq && apt-get install -y -qq build-essential qt5-default gengetopt libelf-dev

spicsim:
  script:
    - make
  artifacts:
    paths:
      - spicsim
